### ISSUE TITLE
No module named 'gsplat'

### ISSUE THREAD

**Issue by sillybirrrd** [facebookresearch/goliath#13]
Hi, thanks for sharing the excellent work! I met a bug when I tried to reproduce the RGCA, it seems like the 'gsplat' module is not provided in the codebase. Could you please provide access to this module?

**Comment by una-dinosauria** [comment]
Please compile the required extensions: https://github.com/facebookresearch/goliath?tab=readme-ov-file#compiling-and-installing-extensions

**Comment by sillybirrrd** [comment]
> Please compile the required extensions: https://github.com/facebookresearch/goliath?tab=readme-ov-file#compiling-and-installing-extensions

Yes, I installed all extensions, including mvpraymarch, sgutils and utils, but there is no extension called 'gsplat', is there anything I miss? Thanks in advance!
![image](https://github.com/user-attachments/assets/53420fe2-39a6-4205-b33a-0ddb81542973)

**Comment by shunsukesaito** [comment]
I forgot to add it to requirements.txt. Now it's updated. You can just install this one
https://github.com/nerfstudio-project/gsplat

**Comment by sillybirrrd** [comment]
> I forgot to add it to requirements.txt. Now it's updated. You can just install this one https://github.com/nerfstudio-project/gsplat

Thanks for your quick response! By the way, it would be better to specify the version of 'gsplat', since its code structure of the latest version is incompatible with this codebase, v0.1.11 works fine for me.

**Comment by dafei-qin** [comment]
Yes the latest version of 'gsplat' leads to **ImportError**:

> ImportError: cannot import name 'project_gaussians' from 'gsplat'

**Comment by una-dinosauria** [comment]
I tried to upgrade to gsplat >= 1.0 but ran into some issues with training (see https://github.com/facebookresearch/goliath/pull/24). If you wanna build upon that PR we can merge! Otherwise you should downgrade gsplat.
