### ISSUE TITLE
ImportError in sgutils(undefined symbol: _ZN3c104cuda9SetDeviceEi)

### ISSUE THREAD

**Issue by dailinyuan1** [facebookresearch/goliath#23]
when I use it in an other project. It seems have something wrong. :
ImportError       (note: full exception trace is shown but execution is paused at: _run_module_as_main)
/home/guoyang/GMS/gaussian-mesh-splatting/extensions/sgutils/sgutilslib.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

**Comment by una-dinosauria** [comment]
You should probably re-compile the extensions wherever you are trying to run the code.

**Comment by dailinyuan1** [comment]
> You should probably re-compile the extensions wherever you are trying to run the code.



> You should probably re-compile the extensions wherever you are trying to run the code.

Thank you for your response! I have resolved the issue. The problem was caused by a mismatch between the CUDA version used by the PyTorch in my virtual environment and the CUDA version of the system.

**Comment by una-dinosauria** [comment]
Thanks for sharing your solution! Closing this issue now.
